# Generated by Django 4.1.7 on 2023-06-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telcontacto', models.IntegerField(max_length=9)),
                ('fechaseminario', models.DateField()),
                ('empresa', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=50)),
            ],
        ),
    ]
